language: node_js
node_js:
  - "9.0.0"

# before_install:
# - sudo apt-get update -qq
# - sudo apt-get install -qq build-essential python

compiler: gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.7
      - g++-4.7

before_install:
  - npm config set python `which python`
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CC="gcc-4.7";
      export CXX="g++-4.7";
      export LINK="gcc-4.7";
      export LINKXX="g++-4.7";
    fi
  - nvm --version
  - node --version
  - npm --version
  - gcc --version
  - g++ --version